# Generated by Django 4.1 on 2022-09-09 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_tareas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_tarea", models.CharField(default="", max_length=128)),
                ("descripcion", models.CharField(default="", max_length=256)),
                ("fecha_creacion", models.DateField(default=datetime.date.today)),
                ("fecha_entrega", models.DateField(null=True)),
                ("usuario_responsable", models.CharField(default="", max_length=128)),
                ("estadoTarea", models.CharField(default="Progreso", max_length=128)),
                #("estadoTarea", models.CharField(choices=[('progreso', 'Progreso'), ('finalizando', 'Finalizando'), ('finalizado', 'Finalizado'), ('pendiente', 'Pendiente')], max_length=10)),
            ],
        ),
    ]
